SPRITE_SCALING = 0.1
BLOCK_SCALING = SPRITE_SCALING * 15

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

SPRITE_PIXEL_SIZE = 52
SPRITE_SIZE = int(SPRITE_PIXEL_SIZE * SPRITE_SCALING)
BLOCK_SIZE = int(SPRITE_PIXEL_SIZE * BLOCK_SCALING)

VIEWPORT_MARGIN = 40
RIGHT_MARGIN = 400

MOVEMENT_SPEED = 4 + 1
JUMP_SPEED = 14
GRAVITY = 0.5

WIN_SCORE = 1